[package]
name = "bastion-cli"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Hansen <alex@bitzmc.com>"]

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
bastion = { path = "../" }
